name: "Java Runner"

description: "Compile and run Java program"

inputs:
  file-name:
    description: "Java file name"
    required: true

runs:
  using: "composite"

  steps:

    - name: Compile Java File
      run: javac ${{inputs.calculatertest}}.java
      shell: bash

    - name: Run Java Program
      run: java ${{inputs.calculatertest}}
      shell: bash