name: "Java Buid Action"

description: "Compile and run Java program"

inputs:
  file-name:
    description: "Java file name"
    required: true

outputs:
  result:
    description: "Build result"

runs:
  using: "composite"

  steps:
    - name: Compile Java
      run: javac ${{inputs.file-name}}.java
      shell: bash

    - name: Run Java Program
      run: java ${{inputs.file-name}}
      shell: bash 

    - name: Set Output
      run: echo "result=Build Successful">> $GITHUB_OUTPUT
      shell: bash
